// <auto-generated />
using System;
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(MatchTrackerDbContext))]
    [Migration("20260514061329_AddAnnotationsAndScheduledMatches")]
    partial class AddAnnotationsAndScheduledMatches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("Data.Models.MatchPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Goals")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MatchRecordId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchRecordId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("Data.Models.MatchRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("GoalsTeamA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsTeamB")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MatchHeld")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayingFieldId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasMatchHeld")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayingFieldId");

                    b.ToTable("MatchRecords");
                });

            modelBuilder.Entity("Data.Models.MatchVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatchRecordId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("VotedHeld")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchRecordId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchVotes");
                });

            modelBuilder.Entity("Data.Models.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartyDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerCreatedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredLocations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCreatedId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("Data.Models.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferredPosition")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Data.Models.PlayerRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatchPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerGivingRatingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerReceivingRatingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchPlayerId")
                        .IsUnique();

                    b.HasIndex("PlayerGivingRatingId");

                    b.HasIndex("PlayerReceivingRatingId");

                    b.ToTable("PlayerRatings");
                });

            modelBuilder.Entity("Data.Models.PlayingField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CountOfPlayedMatches")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsOutdoor")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SurfaceType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlayingFields");
                });

            modelBuilder.Entity("Data.Models.PreferredPlayingDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.ToTable("PreferredPlayingDates");
                });

            modelBuilder.Entity("Data.Models.ScheduledMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayingFieldId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartyId")
                        .IsUnique();

                    b.HasIndex("PlayingFieldId");

                    b.ToTable("ScheduledMatches");
                });

            modelBuilder.Entity("Data.Models.ScheduledMatchAttendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAttending")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScheduledMatchId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ScheduledMatchId");

                    b.ToTable("ScheduledMatchAttendances");
                });

            modelBuilder.Entity("PartyPlayer", b =>
                {
                    b.Property<Guid>("JoinedPartiesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembersId")
                        .HasColumnType("TEXT");

                    b.HasKey("JoinedPartiesId", "MembersId");

                    b.HasIndex("MembersId");

                    b.ToTable("PartyMembers", (string)null);
                });

            modelBuilder.Entity("Data.Models.MatchPlayer", b =>
                {
                    b.HasOne("Data.Models.MatchRecord", "MatchRecord")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Player", "Player")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchRecord");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Data.Models.MatchRecord", b =>
                {
                    b.HasOne("Data.Models.PlayingField", "PlayingField")
                        .WithMany("MatchRecords")
                        .HasForeignKey("PlayingFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayingField");
                });

            modelBuilder.Entity("Data.Models.MatchVote", b =>
                {
                    b.HasOne("Data.Models.MatchRecord", "MatchRecord")
                        .WithMany("MatchVotes")
                        .HasForeignKey("MatchRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Player", "Player")
                        .WithMany("MatchVotes")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchRecord");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Data.Models.Party", b =>
                {
                    b.HasOne("Data.Models.Player", "PlayerCreated")
                        .WithMany("CreatedParties")
                        .HasForeignKey("PlayerCreatedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerCreated");
                });

            modelBuilder.Entity("Data.Models.PlayerRating", b =>
                {
                    b.HasOne("Data.Models.MatchPlayer", "MatchPlayer")
                        .WithOne("PlayerRating")
                        .HasForeignKey("Data.Models.PlayerRating", "MatchPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Player", "PlayerGivingRating")
                        .WithMany("RatingsGiven")
                        .HasForeignKey("PlayerGivingRatingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Player", "PlayerReceivingRating")
                        .WithMany("RatingsReceived")
                        .HasForeignKey("PlayerReceivingRatingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchPlayer");

                    b.Navigation("PlayerGivingRating");

                    b.Navigation("PlayerReceivingRating");
                });

            modelBuilder.Entity("Data.Models.PreferredPlayingDate", b =>
                {
                    b.HasOne("Data.Models.Party", "Party")
                        .WithMany("PreferredPlayingDates")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Data.Models.ScheduledMatch", b =>
                {
                    b.HasOne("Data.Models.Party", "Party")
                        .WithOne("ScheduledMatch")
                        .HasForeignKey("Data.Models.ScheduledMatch", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.PlayingField", "PlayingField")
                        .WithMany("ScheduledMatches")
                        .HasForeignKey("PlayingFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Party");

                    b.Navigation("PlayingField");
                });

            modelBuilder.Entity("Data.Models.ScheduledMatchAttendance", b =>
                {
                    b.HasOne("Data.Models.Player", "Player")
                        .WithMany("ScheduledMatchAttendances")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.ScheduledMatch", "ScheduledMatch")
                        .WithMany("ScheduledMatchAttendances")
                        .HasForeignKey("ScheduledMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("ScheduledMatch");
                });

            modelBuilder.Entity("PartyPlayer", b =>
                {
                    b.HasOne("Data.Models.Party", null)
                        .WithMany()
                        .HasForeignKey("JoinedPartiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Models.MatchPlayer", b =>
                {
                    b.Navigation("PlayerRating");
                });

            modelBuilder.Entity("Data.Models.MatchRecord", b =>
                {
                    b.Navigation("MatchPlayers");

                    b.Navigation("MatchVotes");
                });

            modelBuilder.Entity("Data.Models.Party", b =>
                {
                    b.Navigation("PreferredPlayingDates");

                    b.Navigation("ScheduledMatch");
                });

            modelBuilder.Entity("Data.Models.Player", b =>
                {
                    b.Navigation("CreatedParties");

                    b.Navigation("MatchPlayers");

                    b.Navigation("MatchVotes");

                    b.Navigation("RatingsGiven");

                    b.Navigation("RatingsReceived");

                    b.Navigation("ScheduledMatchAttendances");
                });

            modelBuilder.Entity("Data.Models.PlayingField", b =>
                {
                    b.Navigation("MatchRecords");

                    b.Navigation("ScheduledMatches");
                });

            modelBuilder.Entity("Data.Models.ScheduledMatch", b =>
                {
                    b.Navigation("ScheduledMatchAttendances");
                });
#pragma warning restore 612, 618
        }
    }
}
